# Generated by Django 2.0.6 on 2018-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='news.Tag', verbose_name='Тэги'),
        ),
    ]
